name: Build s1kd-tools
on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update repositories
      run: sudo apt-get update -qq
    - name: Install dependencies
      run: sudo apt-get install -y -qq libxml2-dev libxslt1-dev vim-common
    - name: make
      run: make

  build-mingw64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MSYS2
          update: true
          install: gcc make pkgconf libxml2-devel libxslt-devel libsystre vim
      - name: make
        run: make CC=gcc
